[package]
name = "network-scanner"
version = "0.1.0"
edition = "2021"
description = "Local network scanner"
authors = ["youngrake"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# CLI
clap = "3.1.6"
